---
output: github_document
---

<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "NEWS-"
)
```

# RavenR

RavenR is an R package for handling Raven hydrologic modelling framework inputs, outputs, and diagnostics. Please contact Robert Chlumsky (rchlumsk@uwaterloo.ca) for any troubleshooting, bug fixes, or recommendations on future releases.

# RavenR 1.0.5

## Bug Fixes

* updated the apply.wyearly function
* fixed a bug in the set of functions for annual.peak.event, annual.peak.event.error, annual.peak.timing.error, annual.volume, cum.plot.flow related to the period.apply function being used with the lubridate date functions
* added which.max.xts to support the bug fixes in second bullet, which ix exactly which.max but returns the expected output for xts objects

# RavenR 1.0.4

## Bug Fixes

* fixed bug in apply.wyearly that was reported by a number of users since the last update
* fixed bug reported in hyd.plot in plotting precip on the secondary y-axis, now uses the prd argument as well to plot to the same period as the hydrographs
