#-----------------------------------------------------------------------------#
#' Write common Raven file header. All lines are Appended.
#'
#' @param filename Name of the file, with extension
#' @param filetype File extension, Encoding, Raven version (e.g. "rvp ASCII Raven 2.9.1")
#' @param author Name of file author (optional)
#' @param creationDate Bool of whether creation date should be added to header. (default TRUE)
#' @param textlen Length of lines (default: 40, used to right-align text)
#'
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export writeRavenRFileInfo
#'
#' @examples
#' \dontrun{}
#' writeRavenRFileInfo(filename = 'HogwartsBasin.rvp',
#'                     filetype = 'rvp ASCII Raven 2.9.1',
#'                     author   = 'Harry Potter')
#'
writeRavenRFileInfo <- function(filename, filetype, author=NULL,
                                creationDate=TRUE, textlen=40) {
  # File Type
  write(paste0(":FileType ", stringPad(filetype, textlen-10)),
        append=TRUE, file=filename)

  # Author
  if (!is.null(author)) {
    write(paste0(":WrittenBy ", stringPad(author, textlen-11)),
          append=TRUE, file=filename)
  }

  # Creation Date
  if (creationDate) {
    dateString <- format(Sys.Date(), '%b %Y')
    write(paste0(":CreationDate ", stringPad(dateString, textlen-14)),
          append=TRUE, file=filename)
  }
}
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
#' Opens/Creates a new file, writes common file header.
#'
#' @param filename Name of the file, with extension
#' @param description File Description (e.g., Basin or project information, R script name)
#' @param filetype File extension, Encoding, Raven version (e.g. "rvp ASCII Raven 2.9.1")
#' @param author Name of file author (optional)
#' @param creationDate Bool of whether creation date should be added to header. (default TRUE)
#' @param linelen length (width) of header, in text characters (default: 74)
#' @param textlen Length of textlines (default: 40, used to right-align text)
#'
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export startRavenRFile
#'
#' @examples
#' \dontrun{}
#' startRavenRFile(filename = 'HogwartsBasin.rvp',
#'                 description = 'Hogwarts River Basin RVP File Generated by HP_FileGen.R'
#'                 filetype = 'rvp ASCII Raven 2.9.1',
#'                 author = 'Harry Potter')
#'
startRavenRFile <- function(filename, description, filetype, author=NULL,
                            creationDate=TRUE, linelen=74, textlen=40) {
  # Some top filler
  write(strrep('#', linelen), append=FALSE, file=filename)

  # Write the important stuff
  writeRavenRFileInfo(filename, filetype=filetype, author=author,
                      creationDate=creationDate, textlen=textlen)

  # Write a little custom description
  write('#', append=TRUE, file=filename)
  write(paste("#",description), append=TRUE, file=filename)
  write(paste("#",strrep('-',linelen-2)), append=TRUE, file=filename)
  write('#', append=TRUE, file=filename)
}
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
#' Pads string with spaces, either right or left justified
#'
#' @param string Text string
#' @param width Number of characters total, including desired spaces
#' @param just 'r' for right, 'l' for left
#'
#' @return Padded string
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export stringPad
#'
#' @examples
#' # Returns '   To the right'
#' stringPad('To the right', 15, just='r')
#'
stringPad <- function(string, width, just='r') {
  slength <- nchar(string)
  padlength <- width - slength
  #-- Break if string is longer than the pad width
  if (padlength < 0) {
    stop('String exceeds total width')
  }
  #-- return a padded string
  if (just == 'r') {
    return(paste0(strrep(' ', padlength),
                  string))
  }
  else if (just == 'l') {
    return(paste0(string), strrep(' ', padlength))
  }
}
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
#' Sets up tables for writing to Raven input files
#'
#' @param attributes array of strings containing attribute/parameter names
#' @param units array of strings with the corresponding units
#' @param df Dataframe of values corresponding to attributes/parameters
#' @param parameters bool, when adding attribues/parameter tag, should ':Parameters' be used instead of ':Attributes'?
#'
#' @return DataFrame
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export df2RavenRTable
#'
#' @examples
#' soil_classes <- data.frame('Attributes' = c('DEFAULT','ALTERNATIVE'),
#'                            'SAND'      = c(0.4316, 0.3000),
#'                            'CLAY'      = c(0.1684, 0.4000),
#'                            'SILT'      = c(0.4000, 0.3000),
#'                            'ORGANIC'   = c(0.0000, 0.0000))
#' attributes <- c('%SAND','%CLAY','%SILT','%ORGANIC')
#' units <-  rep('none',4)
#' soil_classes <- df2RavenRTable(attributes, units, soil_classes)
#' print(soil_classes)
#'
df2RavenRTable <- function(attributes, units, df, parameters=FALSE) {

  # Get new column names
  outnames <- paste0('col',1:length(names(df)))

  # Ensure attributes/parameters in Upper Case
  attributes <- toupper(attributes)

  # Add Attribute and Unit lines (check if necessary, is that even necessary?)
  # TODO: What if a list is passed?
  # TODO: Explicit handling for Attributes vs Parameters
  if (trimws(attributes[1]) != ':ATTRIBUTES' &
      trimws(attributes[1]) != ':PARAMETERS' &
      trimws(attributes[1]) != 'ATTRIBUTES' &
      trimws(attributes[1]) != 'PARAMETERS') {
    if (!parameters){ attributes <- c('  :Attributes', attributes) }
    else { attributes <- c('  :Parameters', attributes) }
  } else if (trimws(attributes[1]) == 'ATTRIBUTES' || trimws(attributes[1]) == ':ATTRIBUTES') {
    attributes[1] <- c('  :Attributes') # Custom spacing
  } else if (trimws(attributes[1]) == 'PARAMETERS' || trimws(attributes[1]) == ':PARAMETERS') {
    attributes[1] <- c('  :Parameters') # Custom spacing
  }

  # Unit line also has custom spacing for proper alignment
  if (toupper(trimws(units[1])) != ':UNITS' &
      toupper(trimws(units[1])) != 'UNITS'){
    units <-  c("  :Units     ", units)
  }else{
    units[1] <- "  :Units     "
  }

  # Break if we're not going to have the right number of things
  if (length(outnames) != length(attributes)) {
    stop('Number of attributes/parameters does not match number of dataframe columns')
  }
  if (length(outnames) != length(units)) {
    stop('Number of units does not match number of dataframe columns')
  }

  # Mix n' match
  outdf <- data.frame(rbind(attributes, units),
                      row.names = NULL, stringsAsFactors = F)
  names(df) <- outnames
  names(outdf) <- outnames

  outdf <- rbind(outdf, df)

  return(outdf)
}
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
#' Writes a nicely formatted tables of Raven attributes/parameters
#'
#' @param filename Name of the file, with extension, to append the table to
#' @param attributes array of strings containing attribute/parameter names
#' @param units array of strings with the corresponding units
#' @param df Dataframe of values corresponding to attributes/parameters
#' @param justify alignment of character columns (default 'right'). See \code{\link{format}}
#' @param sep character(s) used to seperate columns (default ', ')
#' @param ... Extra arguments for \code{\link{write.fwf}}
#'
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export write.RavenTable
#'
#' @examples
#' \dontrun{}
#' soil_classes <- data.frame('Attributes' = c('DEFAULT','ALTERNATIVE'),
#'                            'SAND'      = c(0.4316, 0.3000),
#'                            'CLAY'      = c(0.1684, 0.4000),
#'                            'SILT'      = c(0.4000, 0.3000),
#'                            'ORGANIC'   = c(0.0000, 0.0000))
#' attributes <- c('%SAND','%CLAY','%SILT','%ORGANIC')
#' units <-  rep('none',4)
#' write.RavenTable('Hogwarts.rvp', attributes = attributes, units = units, df = soil_classes)
#'
write.RavenTable <- function(filename, attributes, units, df,
                             justify = 'right', sep = ', ', ...) {

  # Setup
  towrite <- df2RavenRTable(attributes, units, df)

  # Write using write.fwf from gdata
  write.fwf(x = towrite,
            file = filename,
            append = TRUE,
            justify = justify,
            colnames = F,
            sep = sep,
            scientific = T,
            ...)

}
#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#
#' Writes common Raven labeled line to file, with optional value (appends)
#'
#' @param filename character, file name/path to write to, with extension
#' @param label character, (e.g. "SoilClasses")
#' @param value numeric or character, corresponding value written after label (optional)
#' @param digits Number of digits to round value to (optional)
#'
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export write.RavenLabel
#'
#' @examples
#' \dontrun{}
#' write.RavenLabel('Duration', 365, 'Hogwarts.rvi')
write.RavenLabel <- function(filename, label, value=NULL, digits=NULL) {
  if (!is.null(digits)) {
    value <- round(value, digits)
  }
  write(paste0(':',label, ' ', value), filename, append = TRUE)
}
#-----------------------------------------------------------------------------#
