#' Write/Overwrite Raven .rvh (watershed discretization) file.
#'
#' Given an HRU and SubBasin dataframe, writes to the specified .rvh file or, in the case of rvh.overwrite,
#' just overwrites the :SubBasins-:EndSubBasins and :HRUs-:EndHRUs blocks, retaining all other content.
#'
#' @param filename Name of .rvh file, with extension
#' @param SBtable Valid subbasin dataframe with required columns "SBID", "Name", "Downstream_ID", "Profile",
#'   "ReachLength", and "Gauged". Can have additional columns.
#' @param HRUtable Valid HRU dataframe with required columns 'ID', 'Area', 'Elevation', 'Latitude', 'Longitude',
#'    'SBID', 'LandUse', 'Vegetation', 'SoilProfile', 'Terrain', 'Aquifer', 'Slope', and 'Aspect'. Can have additional columns.
#' @param description (optional) Description added after file header
#' @param author (optional) Name of author, to be printed in file header.
#' @param orig_file original .rvh file, if overwriting. Must be different from  that specified by filename.
#'
#' @details
#'   rvn_rvh_write is typically used to create a 'clean' .rvh file. rvh.overwrite is usually used
#'   after reading an original .rvh file and processing the HRU and SubBasin tables, using (e.g., rvh.clean)
#' @return {TRUE}{returns TRUE if function runs properly}
#' @author James R. Craig, University of Waterloo
#' @author Leland Scantlebury
#'
#' @seealso
#' \code{\link{rvn_rvh_read}} for the function used to read in the HRU and SubBasin data
#' \code{\link{rvn_rvh_cleanhrus}} for the function used to process HRU dataframe\cr
#' For generating blank SubBasin and HRU tables, see: \code{\link{rvn_rvh_blankSBdf}} and \code{\link{rvn_rvh_blankHRUdf}}\cr
#' See also the \href{http://raven.uwaterloo.ca/}{Raven web site}
#' @examples
#' \dontrun{
#' # Create some blank tables
#' sbs_data <- rvn_rvh_blankSBdf(nSubBasins = 1)
#' HRU_data <- rvn_rvh_blankHRUdf(nHRUs = 3)
#'
#' # Write to files
#' rvn_rvh_write('Output/BigRiver.rvh',
#'               SBtable = sbs_data,
#'               HRUtable = hru_data,
#'               description = 'Big River Watershed Discretization File',
#'               author = 'Raven Baxter')
#'
#' # Read in rvh file, clean contents and write back to new file
#' rvh <- rvn_rvh_read("model.rvh")
#' rvh <- rvn_rvh_cleanhrus(rvh$HRUtable,rvh$SBtable)
#' rvh.overwrite("cleanmodel.rvh","model.rvh",rvh$HRUtable,rvh$SBtable)
#' rvn_rvh_write("nostrings.rvh",rvh$HRUtable,rvh$SBtable)
#'}
#' @keywords Raven  rvh  HRUs write
#' @export rvn_rvh_write
rvn_rvh_write <- function(filename, SBtable, HRUtable, description="Generated by RavenR rvn_rvh_write",
                        author=NULL, ...){
  rvn_newfile(filename = filename,
              description,
              filetype='.rvh',
              author = author,
              ...)
  #-- SubBasins
  write.RavenLabel('SubBasins',filename)
  write.RavenTable(attributes = c('Attributes','NAME','DOWNSTREAM_ID','PROFILE','REACH_LENGTH','GAUGED'),
                   units = c('Units','none','none','none','km','none'),
                   df = SBtable[c('SBID','Name','Downstream_ID','Profile','ReachLength','Gauged')],
                   filename = filename)
  write.RavenLabel('EndSubBasins\n',filename)

  #-- HRUs
  write.RavenLabel("HRUs",filename)
  write.RavenTable(attributes = c('Attributes','AREA', 'ELEVATION','LATITUDE','LONGITUDE','BASIN_ID','LAND_USE_CLASS',
                                  'VEG_CLASS','SOIL_PROFILE','AQUIFER_PROFILE','TERRAIN_CLASS','SLOPE','ASPECT'),
                   units = c('Units','km2','masl','deg','deg','none','none','none','none','none','none','deg','degN'),
                   df = HRUtable[c('ID','Area','Elevation','Latitude','Longitude','SBID','LandUse',
                                   'Vegetation','SoilProfile','Terrain','Aquifer','Slope','Aspect')],
                   filename = filename)
  write.RavenLabel("EndHRUs\n", filename)
}

#-----------------------------------------------------------------------------#

#' @describeIn rvn_rvh_write Overwrite contents of original .rvh file
#' @export rvn_rvh_write
rvh.overwrite<-function(orig_file,filename,SBtable,HRUtable)
{
  write("# -----------------------------------------------------",append=FALSE,file=filename)
  write("# .rvh file modified by RavenR rvh.overwrite.R utility ",append=TRUE,file=filename)
  write("# -----------------------------------------------------",append=TRUE,file=filename)

  lineno<-grep(":SubBasins", readLines(orig_file), value = FALSE)
  lineend<-grep(":EndSubBasins", readLines(orig_file), value = FALSE)
  lines=readLines(orig_file)
  a<-1:length(lines)

  noSB<-lines[!  a %in% (lineno+1):(lineend-1) ] # trim out SB table contents

  lineno<-grep(":HRUs", noSB, value = FALSE)
  lineend<-grep(":EndHRUs", noSB, value = FALSE)
  a<-1:length(noSB)

  noHRUs<-noSB[! a %in% (lineno+1):(lineend-1) ] # trim out HRU table contents


  SBstr<-grep(":SubBasins", noHRUs, value = FALSE)
  SBend<-grep(":EndSubBasins", noHRUs, value = FALSE)
  HRUstr<-grep(":HRUs", noHRUs, value = FALSE)
  HRUend<-grep(":EndHRUs", noHRUs, value = FALSE)

  #insert SB contents
  write(noHRUs[1:SBstr],append=TRUE,file=filename)
  write("  :Properties,SBID,Name,Downstream_ID,Profile,ReachLength,Gauged",append=TRUE,file=filename)
  write("  :Units			     ,none,none         ,none		,km				  ,none",append=TRUE,file=filename)
  write.table(SBtable[c('SBID','Name','Downstream_ID','Profile','ReachLength','Gauged')],quote=FALSE,row.names=FALSE,col.names=FALSE,sep=", ",append=TRUE,file=filename)

  write(noHRUs[SBend:HRUstr],append=TRUE,file=filename)

  write("  :Attributes,AREA, ELEVATION,LATITUDE,LONGITUDE,BASIN_ID,LAND_USE_CLASS,VEG_CLASS,SOIL_PROFILE,AQUIFER_PROFILE,TERRAIN_CLASS,SLOPE,ASPECT",append=TRUE,file=filename)
  write("  :Units			,km2 , masl     ,deg		 ,deg      ,none		,none          ,none     ,none        ,none           ,none         ,deg  ,degN",append=TRUE,file=filename)

  write.table(HRUtable[c('ID','Area','Elevation','Latitude','Longitude','SBID','LandUse','Vegetation','SoilProfile','Terrain','Aquifer','Slope','Aspect')],quote=FALSE,row.names=FALSE,col.names=FALSE,sep=", ",append=TRUE,file=filename)

  write(noHRUs[HRUend:length(noHRUs)],append=TRUE,file=filename)

  return(TRUE)
}

#-----------------------------------------------------------------------------#

#' Generate Blank Raven SubBasin DataFrame
#'
#' @param nSubBasins Number of SubBasins in model, used to determine number of rows in table (default = 1)
#'
#' @return data.frame of blank SubBasin properties to be filled in by user
#' @author Leland Scantlebury
#' @export rvn_rvh_blankSBdf
#'
#' @examples
#' SBtable <- rvn_rvh_blankSBdf(nSubBasins = 1)
rvn_rvh_blankSBdf <- function(nSubBasins = 1) {
  df <- data.frame('SBID'          = 1:nSubBasins,
                   'Name'          = NA,
                   'Downstream_ID' = -1,
                   'Profile'       = "DEFAULT",
                   'ReachLength'   = 0.0,
                   'Gauged'        = 0)
  return(df)
}

#-----------------------------------------------------------------------------#

#' Generate Blank Raven HRU DataFrame
#'
#' Used to generate a blank HRU table that can be filled in by the user. Compatible with
#' rvn_rvh_write().
#'
#' @param nHRUs Number of HRUs, used to determine number of rows in table (default = 1)
#' @param subbasinIDs Subbasins that HRUs belong to (default = all equal 1)
#'
#' @return data.frame of blank HRU properties to be filled in by user
#' @author Leland Scantlebury
#' @export rvn_rvh_blankHRUdf
#'
#' @examples
#' HRUtable <- rvn_rvh_blankHRUdf(nHRUs = 3, subbasinIDs=c(1,1,2))
rvn_rvh_blankHRUdf <- function(nHRUs = 1, subbasinIDs=NULL) {
  if (is.null(subbasinIDs)) {
    subbasinIDs <- rep(1, nHRUs)
  }

  #-- default is zero for numbers, NA for text
  df <- data.frame('ID'         = 1:nHRUs,
                   'Area'       = 0.0,
                   'Elevation'  = 0.0,
                   'Latitude'   = 0.0,
                   'Longitude'  = 0.0,
                   'SBID'       = subbasinIDs,
                   'LandUse'    = NA,
                   'Vegetation' = NA,
                   'SoilProfile'= NA,
                   'Terrain'    = "[NONE]",
                   'Aquifer'    = NA,
                   'Slope'      = 0.0,
                   'Aspect'     = 0.0)
  #-- Nothing fancy
  return(df)
}
