#' Read in Raven Hydrograph file
#'
#' rvn_hyd_dygraph plots modeled vs observed hydrographs when supplied with hydrograph data
#' structure read using rvn_hyd_read()
#'
#' @param hy hydrograph data structure generated by rvn_hyd_read() routine
#' @param timezone data timezone; defaults to UTC
#' @param basins list of subbasin names from hydrograph file. Each subbasin creates separate dygraph plots
#' @param figheight height of figure, in pixels
#'
#' @return {res}{a list of plot handles to dygraph plots}
#'
#' See also \href{http://raven.uwaterloo.ca/}{Raven page}
#' @keywords Raven hydrograph plotting
#' @examples
#'
#' # read in RavenR sample hydrographs data
#' hy <- rvn_hydrograph_data
#'
#' # view contents for subbasin 36 as dyGraph
#' res<-rvn_hyd_dygraph(hy,basins="sub36")
#'
#' @export rvn_hyd_dygraph
rvn_hyd_dygraph <- function(hy, timezone="UTC",basins="", figheight=400)
{

  if (basins==""){
    basins<-sub('_obs', "", colnames(hy$hyd))
    basins<-sub('_res', "", basins)
    basins<-unique(basins)
    basins<-basins[-1] # no precip ts
  }

  plotfunc <- function(basin){
    hyd <- hyd.extract(subs = basin, hyd = hy)
    flow <- merge(hyd$sim, hyd$obs)
    return(dygraph(flow, group = 'flows', main = basin, height=figheight) %>%
             dyRangeSelector())
  }

  res <- map(basins, plotfunc) # calls plotfunc for each basin in list basins
  return(res)
}
