#' Calculates Yearly Median, Upper and Lower Quantiles of Flow
#'
#' @param hgdata Time series object of observed or simulated flows
#' @param minyear Integer of minimum year (optional)
#' @param maxyear Integer of maximum year (optional)
#' @param Qlower Decimal percentage of lower quantile value (default 0.1)
#' @param Qupper Decimal percentage of upper quantile value (default 0.9)
#'
#' @return Time series object of monthly median and quantile values
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export rvn_yearly_quantile
#'
#' @examples
#' data("rvn_hydrograph_data")
#'
#' # Pull out a specific hydrograph
#' hgdata <- hydrograph.data$hyd$Sub36
#'
#' # Calculate quantiles
#' qdat <- rvn_yearly_quantile(hgdata)
#'
rvn_yearly_quantile <- function(hgdata, minyear=NULL, maxyear=NULL,
                           Qlower=0.1, Qupper=0.9, water_year=T) {

  #-- Assuming hgdata is a daily xts object
  # TODO: Add support for other frequencies

  #-- Handle if no min/max passed
  if (is.null(minyear)) { minyear <- year(start(hgdata))}
  if (is.null(maxyear)) { maxyear <- year(end(hgdata))}

  #-- Subset by date
  hgdata <- hgdata[paste0(toString(minyear),"/",toString(maxyear))]

  #-- Aggregate to Quantiles by Day
  # (Uses maxyear as placeholder for year)
  monthday <- as.Date(paste0(toString(maxyear), "-", month(hgdata), "-", day(hgdata)))
  if (water_year) {
    # Year is arbitrary, so subtract a year post-Oct to create water years
    monthday[month(monthday) > 9] = monthday[month(monthday) > 9] - years(1)
  }
  qdat <- xts(aggregate(hgdata, by=monthday, quantile,
                        probs=c(Qlower, .5, Qupper), na.rm=T))

  return(qdat)
}

#--------------------------------------------------------------------------

#' Plot of Yearly Median, Upper and Lower Quantiles of Flow
#'
#' @param qdat Time series object generated by yearly_quantile()
#' @param mediancolor Color for the median line
#' @param ribboncolor Color for the lower/upper quantile ribbon
#' @param ribbonalpha Transparency of lower/upper quantile ribbon
#' @param addtoplot Existing ggplot object to which median line and quantile ribbon should be added
#'
#' @return Monthly Plot
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export rvn_yearly_quantile_plot
#'
#' @examples
#' data(hydrograph.data)
#'
#' # Pull out a specific hydrograph
#' hgdata <- rvn_hydrograph_data$hyd$Sub36_obs
#'
#' # Calculate quantiles
#' qdat <- yearly_quantile(hgdata)
#'
#' # Plot
#' p <- rvn_yearly_quantile_plot(qdat)
#' p  # To view
#'
#' # Add a second hydrograph to compare
#' simdata <- rvn_hydrograph_data$hyd$Sub36
#' qdat_sim <- yearly_quantile(hgdata)
#'
#' p <- rvn_yearly_quantile_plot(qdat_sim, mediancolor = 'red', ribboncolor = 'red', addtoplot = p)
#' p # To view
rvn_yearly_quantile_plot <- function(qdat, mediancolor='black', ribboncolor='grey60', ribbonalpha=0.5, addtoplot=NULL) {

  # Export XTS object into df
  dates <- date(qdat)
  qdat <- data.frame(qdat)
  qdat$date <- dates

  # Rename Columns
  names(qdat) <- c('Lower','Median','Upper','date')

  if(is.null(addtoplot)) {
    p <- ggplot(qdat, aes(x = date)) +
      geom_ribbon(aes(ymin=Lower, ymax=Upper), fill=ribboncolor, alpha=ribbonalpha) +
      geom_line(aes(y=Median), color=mediancolor) +
      scale_x_date(labels = date_format("%b")) +
      labs(x = 'Day of Year', y = expression(Daily~Streamflow~(m^3/s)))
  } else {
    p <- p + geom_ribbon(data=qdat, aes(ymin=Lower, ymax=Upper), fill=ribboncolor, alpha=ribbonalpha) +
      geom_line(data=qdat, aes(y=Median), color=mediancolor)
  }

  return(p)
}
