#' Plot Raven reservoir/lake stage time series using dygraph
#'
#' rvn_res_dygraph plots modeled vs observed stage plots when supplied with reservoir stage data
#' structure read using hyd.read()
#'
#' @param resdata reservoir stage time series data structure generated by res.read() routine
#' @param timezone data timezone; defaults to UTC
#' @param basins list of subbasin names from reservoir file. Each subbasin creates separate dygraph plots
#' @param figheight height of figure, in pixels
#'
#' @return a list of plot handles to dygraph plots
#'
#' See also \href{http://raven.uwaterloo.ca/}{Raven page}
#' @keywords Raven reservoir stage plotting
#' @examples
#'
#' # read in Raven Reservoir Stages file
#' resdata<-res.read("C:/TEMP/ReservoirStages.csv")
#'
#' # view contents for all subbasins as dyGraph
#' res<-res.dyGraphs(resdata,basins="sub11")
#' res[0]
#' res[1]
#'
#' @export rvn_res_dygraph
rvn_res_dygraph <- function(resdata, timezone="UTC",basins="", figheight=400)
{
  if (basins==""){ # plots all reservoirs
    basins<-sub('_obs', "", colnames(resdata$res)) #replace _obs
    basins<-unique(basins) #gets rid of repeats with
    basins<-basins[-1] # no precip ts
  }

  plotfunc <- function(basin){
    stagets <- res.extract(subs = basin, res = resdata)
    stage <- merge(stagets$sim, stagets$obs) #not inflow
    print (basin)
    return(
      dygraph(stage, group = 'stages', main = basin, height=figheight) %>%
             dyRangeSelector()
    )
  }
  res <- map(basins, plotfunc) # calls plotfunc for each basin in list basins
  return(res)
}


