#' Plot of Yearly Median, Upper and Lower Quantiles of Flow
#'
#' @param qdat Time series object generated by rvn_annual_quantiles()
#' @param mediancolor Color for the median line
#' @param ribboncolor Color for the lower/upper quantile ribbon
#' @param ribbonalpha Transparency of lower/upper quantile ribbon
#' @param addtoplot Existing ggplot object to which median line and quantile ribbon should be added
#'
#' @return Monthly Plot
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#'
#' @examples
#' data(hydrograph.data)
#'
#' # Pull out a specific hydrograph
#' hgdata <- rvn_hydrograph_data$hyd$Sub36_obs
#'
#' # Calculate quantiles
#' qdat <- yearly_quantile(hgdata)
#'
#' # Plot
#' p <- rvn_yearly_quantile_plot(qdat)
#' p  # To view
#'
#' # Add a second hydrograph to compare
#' simdata <- rvn_hydrograph_data$hyd$Sub36
#' qdat_sim <- rvn_annual_quantiles(hgdata)
#'
#' p <- rvn_annual_quantiles_plot(qdat_sim, mediancolor = 'red', ribboncolor = 'red', addtoplot = p)
#' p # To view
#' @export rvn_annual_quantiles_plot
rvn_annual_quantiles_plot <- function(qdat, mediancolor='black', ribboncolor='grey60', ribbonalpha=0.5, addtoplot=NULL) {

  # Export XTS object into df
  dates <- date(qdat)
  qdat <- data.frame(qdat)
  qdat$date <- dates

  # Rename Columns
  names(qdat) <- c('Lower','Median','Upper','date')

  if(is.null(addtoplot)) {
    p1 <- ggplot(qdat, aes(x = date)) +
      geom_ribbon(aes(ymin=Lower, ymax=Upper), fill=ribboncolor, alpha=ribbonalpha) +
      geom_line(aes(y=Median), color=mediancolor) +
      scale_x_date(labels = date_format("%b")) +
      labs(x = 'Day of Year', y = expression(Daily~Streamflow~(m^3/s)))
  } else {
    p1 <- p1 + geom_ribbon(data=qdat, aes(ymin=Lower, ymax=Upper), fill=ribboncolor, alpha=ribbonalpha) +
      geom_line(data=qdat, aes(y=Median), color=mediancolor)
  }

  return(p)
}
