#' Calculates Yearly Median, Upper and Lower Quantiles of Flow
#'
#' @param hgdata Time series object of observed or simulated flows
#' @param minyear Integer of minimum year
#' @param maxyear Integer of maximum year
#' @param Qlower Decimal percentage of lower quantile value (default 0.1)
#' @param Qupper Decimal percentage of upper quantile value (default 0.9)
#'
#' @return Time series object of monthly median and quantile values
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export yearly_quantile
#'
#' @examples
#' data(hydrograph.data)
#'
#' # Pull out a specific hydrograph
#' hgdata <- hydrograph.data$hyd$Sub36
#'
#' # Calculate quantiles
#' qdat <- yearly_quantile(hgdata)
#'
yearly_quantile <- function(hgdata, minyear=NULL, maxyear=NULL,
                           Qlower=0.1, Qupper=0.9) {

  #-- Assuming hgdata is a daily xts object
  # TODO: Add support for other frequencies

  #-- Handle if no min/max passed
  if (is.null(minyear)) { minyear <- year(start(hgdata))}
  if (is.null(maxyear)) { maxyear <- year(end(hgdata))}

  #-- Subset by date
  hgdata <- hgdata[paste0(toString(minyear),"/",toString(maxyear))]

  #-- Aggregate to Quantiles by Day
  # (Uses maxyear as placeholder for year)
  monthday <- as.Date(paste0(toString(maxyear), "-", month(hgdata), "-", day(hgdata)))
  qdat <- xts(aggregate(hgdata, by=monthday, quantile,
                        probs=c(Qlower, .5, Qupper), na.rm=T))

  return(qdat)
}

#--------------------------------------------------------------------------

#' Plot of Yearly Median, Upper and Lower Quantiles of Flow
#'
#' @param qdat Time series object generated by yearlyquantile()
#' @param mediancolor Color for the median line
#' @param qcolor Color for the lower/upper quantile "ribbon"
#' @param zero.axis Fixes the y axis to start exactly at zero (default TRUE)
#' @param leg.pos String specifying legend placement on plot
#' @param leg.box Boolean on whether to put legend in an opaque box
#'
#' @return Monthly Plot
#' @author Leland Scantlebury, \email{leland@@scantle.com}
#' @export rvn_yearly_quantile_plot
#'
#' @examples
#' data(hydrograph.data)
#'
#' # Pull out a specific hydrograph
#' hgdata <- hydrograph.data$hyd$Sub36
#'
#' # Calculate quantiles
#' qdat <- yearly_quantile(hgdata)
#'
#' # Plot
#' rvn_yearly_quantile_plot(qdat)
rvn_yearly_quantile_plot <- function(qdat, mediancolor='black', qcolor='grey60') {

  # Export XTS object into df
  dates <- date(qdat)
  qdat <- data.frame(qdat)
  qdat$date <- dates

  # Rename Columns
  names(qdat) <- c('Lower','Median','Upper','date')

  p <- ggplot(qdat, aes(x = date)) +
    geom_ribbon(aes(ymin=Lower, ymax=Upper), fill=qcolor, alpha=0.5) +
    geom_line(aes(y=Median), color=mediancolor) +
    labs(x = 'Day of Year', y = expression(Daily~Streamflow~(m^3/s)))

  return(p)
}
